# Generated by Django 5.0.1 on 2024-02-22 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_diagnosis_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosis',
            name='patient_name',
            field=models.CharField(max_length=100),
        ),
    ]
