# Generated by Django 5.0.1 on 2024-02-29 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosis',
            name='patient_date_of_birth',
            field=models.DateTimeField(),
        ),
    ]
